'use client';
import {useEffect,useMemo,useState} from 'react';
import {usePathname,useRouter} from 'next/navigation';
import {ArrowLeftIcon,ArrowRightIcon,BookOpenIcon,CheckIcon,Cog6ToothIcon,DocumentTextIcon,HeartIcon,HomeIcon,LightBulbIcon,MagnifyingGlassIcon,MapIcon,PlusIcon,SparklesIcon,TrashIcon,UsersIcon,XMarkIcon} from '@heroicons/react/24/outline';
import {demoProjects,emptyProject} from '@/lib/data';
import {uid} from '@/lib/id';
import type {Chapter,Character,GenericItem,Idea,Project,Scene,WritingDocument} from '@/lib/types';

const KEY='story-atelier-projects';
const labels:Record<string,string>={short_story:'Short story',young_adult:'Young adult',to_write:'To write',needs_revision:'Needs revision',side_character:'Side character',love_interest:'Love interest'};
const pretty=(s:string)=>labels[s]||s.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const stamp=()=>new Date().toISOString();
const words=(s='')=>s.trim()?s.trim().split(/\s+/).length:0;

export default function StoryAtelier(){
 const pathname=usePathname(),router=useRouter();
 const [projects,setProjects]=useState<Project[]>([]),[ready,setReady]=useState(false),[toast,setToast]=useState('');
 useEffect(()=>{try{const saved=localStorage.getItem(KEY);setProjects(saved?JSON.parse(saved):demoProjects)}catch{setProjects(demoProjects)}setReady(true)},[]);
 useEffect(()=>{if(ready)localStorage.setItem(KEY,JSON.stringify(projects))},[projects,ready]);
 const go=(p:string)=>router.push(p);
 const flash=(t:string)=>{setToast(t);setTimeout(()=>setToast(''),1800)};
 const update=(id:string,fn:(p:Project)=>Project)=>setProjects(ps=>ps.map(p=>p.id===id?{...fn(p),updatedAt:stamp()}:p));
 const parts=pathname.split('/').filter(Boolean),projectId=parts[1],section=parts[2];
 const project=projects.find(p=>p.id===projectId);
 if(!ready)return <div className="loading"><SparklesIcon/>Preparing your atelier…</div>;
 let content:React.ReactNode;
 if(pathname==='/')content=<Dashboard projects={projects} go={go}/>;
 else if(pathname==='/projects/new')content=<NewProject onCreate={p=>{setProjects(x=>[p,...x]);go(`/projects/${p.id}`);flash('Your new story is ready')}} go={go}/>;
 else if(project) content=section?<SectionPage project={project} section={section} update={fn=>update(project.id,fn)} go={go} flash={flash} removeProject={()=>{if(confirm('Delete this project and everything inside it?')){setProjects(x=>x.filter(p=>p.id!==project.id));go('/')}}}/>:<ProjectHome project={project} go={go}/>;
 else content=<NotFound go={go}/>;
 return <div className="app"><Header go={go} project={project}/>{content}<MobileNav go={go} project={project}/>{toast&&<div className="toast"><CheckIcon/>{toast}</div>}</div>
}

function Header({go,project}:{go:(s:string)=>void;project?:Project}){return <header className="topbar"><button className="brand" onClick={()=>go('/')}><span className="brandmark"><SparklesIcon/></span><span>Story Atelier</span></button><nav><button onClick={()=>go('/')}>Dashboard</button>{project&&<><button onClick={()=>go(`/projects/${project.id}`)}>Project</button><button onClick={()=>go(`/projects/${project.id}/ideas`)}>Ideas</button></>}</nav><button className="avatar" aria-label="Profile">RA</button></header>}

function Dashboard({projects,go}:{projects:Project[];go:(s:string)=>void}){
 const allWords=projects.flatMap(p=>p.writingDocuments).reduce((n,d)=>n+d.wordCount,0)+projects.flatMap(p=>p.chapters).reduce((n,c)=>n+(c.wordCount||0),0);
 const stats=[['Active projects',projects.filter(p=>p.status!=='finished').length,BookOpenIcon],['Total words',allWords.toLocaleString(),DocumentTextIcon],['Ideas',projects.reduce((n,p)=>n+p.randomIdeas.length,0),LightBulbIcon],['Characters',projects.reduce((n,p)=>n+p.characters.length,0),UsersIcon]] as const;
 return <main className="page"><section className="hero"><div><p className="eyebrow">The atelier</p><h1>Welcome back to<br/><em>your stories.</em></h1><p>Your characters are waiting where you left them. Ready to dive back in?</p></div><button className="primary" onClick={()=>go('/projects/new')}><PlusIcon/>New project</button></section>
 <section className="statgrid">{stats.map(([l,v,I])=><article className="stat" key={l}><span><I/></span><small>{l}</small><strong>{v}</strong></article>)}</section>
 <div className="sectionhead"><div><p className="eyebrow">On your desk</p><h2>Your projects</h2></div><span>{projects.length} stories</span></div>
 <section className="projectgrid">{projects.map((p,i)=><button className="projectcard" key={p.id} onClick={()=>go(`/projects/${p.id}`)}><div className={`cover cover${i%3}`} style={p.coverUrl?{backgroundImage:`linear-gradient(180deg,transparent,rgba(36,22,31,.65)),url(${p.coverUrl})`}:undefined}><span>{pretty(p.genre)}</span><b>{p.title}</b></div><div className="projectbody"><div><span className="pill">{pretty(p.type)} · {pretty(p.status)}</span><h3>{p.title}</h3><p>{p.description}</p></div><div className="progresslabel"><span>Progress</span><b>{p.progress||0}%</b></div><div className="progress"><i style={{width:`${p.progress||0}%`}}/></div><footer><span>{p.chapters.length} chapters</span><span>{p.characters.length} characters</span><ArrowRightIcon/></footer></div></button>)}</section></main>
}

function NewProject({onCreate,go}:{onCreate:(p:Project)=>void;go:(s:string)=>void}){const [form,setForm]=useState({title:'',type:'novel',genre:'fantasy',status:'idea',description:'',coverUrl:''});return <main className="page narrow"><button className="back" onClick={()=>go('/')}><ArrowLeftIcon/>Back to dashboard</button><section className="formhero"><p className="eyebrow">A blank page</p><h1>Begin your journey</h1><p>Every story starts with a name and a spark. The rest can arrive slowly.</p></section><form className="paperform" onSubmit={e=>{e.preventDefault();if(!form.title.trim())return;onCreate(emptyProject(form as Partial<Project>))}}><Field label="Project title"><input required autoFocus placeholder="The name of your story" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></Field><div className="formrow"><Field label="Format"><Select value={form.type} onChange={v=>setForm({...form,type:v})} options={['novel','short_story','saga','collection','other']}/></Field><Field label="Genre"><Select value={form.genre} onChange={v=>setForm({...form,genre:v})} options={['fantasy','romance','thriller','drama','young_adult','contemporary','other']}/></Field><Field label="Stage"><Select value={form.status} onChange={v=>setForm({...form,status:v})} options={['idea','planning','drafting','editing','finished']}/></Field></div><Field label="A few words about it"><textarea rows={4} placeholder="What is this story reaching for?" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field><Field label="Cover image URL (optional)"><input placeholder="https://…" value={form.coverUrl} onChange={e=>setForm({...form,coverUrl:e.target.value})}/></Field><div className="formfooter"><span>You can change everything later.</span><button className="primary" type="submit"><SparklesIcon/>Create my story</button></div></form></main>}

const sectionDefs=[['characters','Characters','Meet the people who make the story breathe',UsersIcon],['worldbuilding','Worldbuilding','Places, rules, history and magic',MapIcon],['chapters','Chapter outline','Shape the rhythm of your manuscript',BookOpenIcon],['scenes','Scene board','Move each moment from spark to final',DocumentTextIcon],['relationships','Relationships','Trace the ties that bind and break',HeartIcon],['plot-twists','Plot twists','Hide clues and time your reveals',SparklesIcon],['ideas','Random ideas','Keep every flicker before it disappears',LightBulbIcon],['writing','Writing space','A quiet place to put words on the page',DocumentTextIcon],['structure','Book structure','See the whole arc at a glance',BookOpenIcon],['moodboard','Moodboard','Gather the atmosphere of your world',SparklesIcon],['custom-sections','Custom sections','Make the atelier entirely yours',PlusIcon]] as const;
function ProjectHome({project:p,go}:{project:Project;go:(s:string)=>void}){const wordCount=p.writingDocuments.reduce((n,d)=>n+d.wordCount,0);return <main className="page"><button className="back" onClick={()=>go('/')}><ArrowLeftIcon/>All projects</button><section className="projecthero"><div className="miniCover" style={p.coverUrl?{backgroundImage:`url(${p.coverUrl})`}:undefined}><BookOpenIcon/></div><div><span className="pill">{pretty(p.genre)} · {pretty(p.status)}</span><h1>{p.title}</h1><p>{p.description||'A new story, still full of possibility.'}</p></div><div className="ring" style={{'--p':`${p.progress||0}%`} as React.CSSProperties}><b>{p.progress||0}%</b><small>complete</small></div></section><section className="quickstats"><div><b>{p.characters.length}</b><span>Characters</span></div><div><b>{p.chapters.length}</b><span>Chapters</span></div><div><b>{p.scenes.length}</b><span>Scenes</span></div><div><b>{wordCount}</b><span>Words</span></div><div><b>{p.randomIdeas.length}</b><span>Ideas</span></div></section><div className="sectionhead"><div><p className="eyebrow">Inside your story</p><h2>The workbench</h2></div><button className="ghost" onClick={()=>go(`/projects/${p.id}/settings`)}><Cog6ToothIcon/>Settings</button></div><section className="sectiongrid">{sectionDefs.map(([slug,title,desc,I])=><button key={slug} onClick={()=>go(`/projects/${p.id}/${slug}`)} className="sectioncard"><span><I/></span><div><h3>{title}</h3><p>{desc}</p></div><ArrowRightIcon/></button>)}</section></main>}

function SectionPage({project:p,section,update,go,flash,removeProject}:{project:Project;section:string;update:(fn:(p:Project)=>Project)=>void;go:(s:string)=>void;flash:(s:string)=>void;removeProject:()=>void}){
 const def=sectionDefs.find(x=>x[0]===section);let body:React.ReactNode;
 if(section==='characters')body=<Characters p={p} save={xs=>{update(q=>({...q,characters:xs}));flash('Characters saved')}}/>;
 else if(section==='chapters')body=<Chapters p={p} save={xs=>{update(q=>({...q,chapters:xs,progress:xs.length?Math.round(xs.filter(c=>c.status==='finished').length/xs.length*100):0}));flash('Outline saved')}}/>;
 else if(section==='ideas')body=<Ideas items={p.randomIdeas} save={xs=>{update(q=>({...q,randomIdeas:xs}));flash('Idea tucked away')}}/>;
 else if(section==='writing')body=<Writing p={p} save={xs=>{update(q=>({...q,writingDocuments:xs}));flash('Draft saved')}}/>;
 else if(section==='structure')body=<Structure p={p} save={v=>{update(q=>({...q,bookStructure:v}));flash('Structure saved')}}/>;
 else if(section==='scenes')body=<Scenes items={p.scenes} save={xs=>{update(q=>({...q,scenes:xs}));flash('Scene board saved')}}/>;
 else if(section==='settings')body=<Settings p={p} save={v=>{update(()=>v);flash('Project updated')}} remove={removeProject}/>;
 else {const key=section==='plot-twists'?'plotTwists':section==='custom-sections'?'customSections':section as keyof Project;body=<Generic title={def?.[1]||pretty(section)} items={(p[key] as GenericItem[])||[]} save={xs=>{update(q=>({...q,[key]:xs}));flash('Saved')}}/>}
 return <main className="page"><button className="back" onClick={()=>go(`/projects/${p.id}`)}><ArrowLeftIcon/>{p.title}</button><section className="subhero"><p className="eyebrow">{p.title}</p><h1>{def?.[1]||pretty(section)}</h1><p>{def?.[2]||'Shape the details of your story.'}</p></section>{body}</main>
}

function Characters({p,save}:{p:Project;save:(x:Character[])=>void}){const [query,setQuery]=useState(''),[role,setRole]=useState('all'),[edit,setEdit]=useState<Character|null>(null);const list=p.characters.filter(c=>c.name.toLowerCase().includes(query.toLowerCase())&&(role==='all'||c.role===role));return <><div className="toolbar"><label className="search"><MagnifyingGlassIcon/><input placeholder="Search characters" value={query} onChange={e=>setQuery(e.target.value)}/></label><Select value={role} onChange={setRole} options={['all','protagonist','antagonist','love_interest','side_character','mentor','family','other']}/><button className="primary" onClick={()=>setEdit(newCharacter())}><PlusIcon/>Add character</button></div>{list.length?<section className="charactergrid">{list.map((c,i)=><article className="charcard" key={c.id}><div className={`portrait portrait${i%4}`}>{c.imageUrl?<img src={c.imageUrl} alt=""/>:<span>{c.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</span>}</div><div><span className="pill">{pretty(c.role)}</span><h3>{c.name}</h3><p>{c.personality||c.backstory||'A character waiting to be discovered.'}</p><div className="tags">{c.tags.map(t=><i key={t}>#{t}</i>)}</div><button className="textbtn" onClick={()=>setEdit(c)}>Open profile <ArrowRightIcon/></button></div></article>)}</section>:<Empty icon={UsersIcon} title="No characters here yet" text="Every memorable story begins with someone who wants something." action={()=>setEdit(newCharacter())}/>} {edit&&<CharacterModal item={edit} close={()=>setEdit(null)} save={c=>{save(p.characters.some(x=>x.id===c.id)?p.characters.map(x=>x.id===c.id?c:x):[...p.characters,c]);setEdit(null)}} remove={()=>{save(p.characters.filter(x=>x.id!==edit.id));setEdit(null)}}/>}</>}
const newCharacter=():Character=>({id:uid(),name:'',role:'protagonist',tags:[],createdAt:stamp(),updatedAt:stamp()});
function CharacterModal({item,close,save,remove}:{item:Character;close:()=>void;save:(x:Character)=>void;remove:()=>void}){const [x,setX]=useState(item);return <Modal title={x.name||'New character'} close={close}><div className="modalgrid"><Field label="Name"><input autoFocus value={x.name} onChange={e=>setX({...x,name:e.target.value})}/></Field><Field label="Role"><Select value={x.role} onChange={role=>setX({...x,role})} options={['protagonist','antagonist','love_interest','side_character','mentor','family','other']}/></Field><Field label="Age"><input value={x.age||''} onChange={e=>setX({...x,age:e.target.value})}/></Field><Field label="Tags"><input placeholder="brave, secretive" value={x.tags.join(', ')} onChange={e=>setX({...x,tags:e.target.value.split(',').map(s=>s.trim()).filter(Boolean)})}/></Field></div>{[['personality','Personality'],['appearance','Appearance'],['backstory','Backstory'],['mainGoal','Main goal'],['fear','Fear'],['secret','Secret'],['characterArc','Character arc'],['notes','Notes']].map(([k,l])=><Field label={l} key={k}><textarea rows={2} value={(x as unknown as Record<string,string>)[k]||''} onChange={e=>setX({...x,[k]:e.target.value})}/></Field>)}<ModalActions remove={item.name?remove:undefined} save={()=>x.name.trim()&&save({...x,updatedAt:stamp()})}/></Modal>}

function Chapters({p,save}:{p:Project;save:(x:Chapter[])=>void}){const [edit,setEdit]=useState<Chapter|null>(null);const move=(i:number,d:number)=>{const xs=[...p.chapters],to=i+d;if(to<0||to>=xs.length)return;[xs[i],xs[to]]=[xs[to],xs[i]];save(xs.map((c,j)=>({...c,number:j+1})))};return <>{p.chapters.length?<div className="chapterlist">{p.chapters.map((c,i)=><article key={c.id}><div className="chapternum"><small>Chapter</small><b>{String(c.number).padStart(2,'0')}</b></div><div className="chaptermain"><span className="pill">{pretty(c.status)}</span><h3>{c.title}</h3><p>{c.keyPoints.join(' · ')||c.mainConflict||'No key beats added yet.'}</p><footer><span>{(c.wordCount||0).toLocaleString()} words</span><button onClick={()=>move(i,-1)}>↑</button><button onClick={()=>move(i,1)}>↓</button><button className="textbtn" onClick={()=>setEdit(c)}>Edit <ArrowRightIcon/></button></footer></div></article>)}</div>:<Empty icon={BookOpenIcon} title="Your outline is wide open" text="Add the first chapter—even a temporary title gives the story somewhere to begin." action={()=>setEdit(newChapter(p))}/>}<button className="primary below" onClick={()=>setEdit(newChapter(p))}><PlusIcon/>Add chapter</button>{edit&&<ChapterModal item={edit} close={()=>setEdit(null)} save={c=>{save(p.chapters.some(x=>x.id===c.id)?p.chapters.map(x=>x.id===c.id?c:x):[...p.chapters,c]);setEdit(null)}} remove={()=>{save(p.chapters.filter(x=>x.id!==edit.id).map((c,i)=>({...c,number:i+1})));setEdit(null)}}/>}</>}
const newChapter=(p:Project):Chapter=>({id:uid(),number:p.chapters.length+1,title:'',status:'planned',keyPoints:[],wordCount:0,createdAt:stamp(),updatedAt:stamp()});
function ChapterModal({item,close,save,remove}:{item:Chapter;close:()=>void;save:(x:Chapter)=>void;remove:()=>void}){const [x,setX]=useState(item);return <Modal title={x.title||`Chapter ${x.number}`} close={close}><div className="modalgrid"><Field label="Title"><input autoFocus value={x.title} onChange={e=>setX({...x,title:e.target.value})}/></Field><Field label="Status"><Select value={x.status} onChange={status=>setX({...x,status})} options={['planned','drafted','revised','finished']}/></Field><Field label="Word count"><input type="number" value={x.wordCount||0} onChange={e=>setX({...x,wordCount:+e.target.value})}/></Field></div><Field label="Key points"><textarea rows={3} placeholder="One beat per line" value={x.keyPoints.join('\n')} onChange={e=>setX({...x,keyPoints:e.target.value.split('\n').filter(Boolean)})}/></Field><Field label="Main conflict"><textarea rows={2} value={x.mainConflict||''} onChange={e=>setX({...x,mainConflict:e.target.value})}/></Field><Field label="Emotional beat"><textarea rows={2} value={x.emotionalBeat||''} onChange={e=>setX({...x,emotionalBeat:e.target.value})}/></Field><ModalActions remove={item.title?remove:undefined} save={()=>x.title.trim()&&save({...x,updatedAt:stamp()})}/></Modal>}

function Ideas({items,save}:{items:Idea[];save:(x:Idea[])=>void}){const [text,setText]=useState('');const add=()=>{if(!text.trim())return;save([{id:uid(),text:text.trim(),tags:[],pinned:false,createdAt:stamp(),updatedAt:stamp()},...items]);setText('')};return <><div className="ideaInput"><LightBulbIcon/><textarea rows={2} placeholder="Catch a thought before it wanders off…" value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter')add()}}/><button className="primary" onClick={add}>Keep idea</button></div>{items.length?<div className="ideagrid">{[...items].sort((a,b)=>Number(b.pinned)-Number(a.pinned)).map(x=><article className={x.pinned?'pinned':''} key={x.id}><button className="pin" onClick={()=>save(items.map(i=>i.id===x.id?{...i,pinned:!i.pinned}:i))}>✦</button><p>{x.text}</p><footer><span>{x.tags.map(t=>`#${t}`).join(' ')||'Unsorted spark'}</span><button onClick={()=>confirm('Let this idea go?')&&save(items.filter(i=>i.id!==x.id))}><TrashIcon/></button></footer></article>)}</div>:<Empty icon={LightBulbIcon} title="A lovely, empty idea drawer" text="Use the box above for stray lines, questions, images, and impossible what-ifs."/>}</>}

function Writing({p,save}:{p:Project;save:(x:WritingDocument[])=>void}){const [active,setActive]=useState(p.writingDocuments[0]?.id||''),[focus,setFocus]=useState(false);const doc=p.writingDocuments.find(x=>x.id===active);const patch=(v:Partial<WritingDocument>)=>doc&&save(p.writingDocuments.map(x=>x.id===doc.id?{...x,...v,updatedAt:stamp()}:x));const create=()=>{const d={id:uid(),title:'Untitled draft',content:'',wordCount:0,createdAt:stamp(),updatedAt:stamp()};save([...p.writingDocuments,d]);setActive(d.id)};return <div className={`writer ${focus?'focus':''}`}><aside><div><p className="eyebrow">Documents</p><button onClick={create}><PlusIcon/>New draft</button></div>{p.writingDocuments.map(d=><button className={d.id===active?'active':''} onClick={()=>setActive(d.id)} key={d.id}><DocumentTextIcon/><span>{d.title}<small>{d.wordCount} words</small></span></button>)}</aside>{doc?<section className="editor"><header><input aria-label="Document title" value={doc.title} onChange={e=>patch({title:e.target.value})}/><button className="ghost" onClick={()=>setFocus(!focus)}>{focus?'Exit focus':'Focus mode'}</button></header><textarea aria-label="Writing canvas" placeholder="Start wherever the story feels warm…" value={doc.content} onChange={e=>patch({content:e.target.value,wordCount:words(e.target.value)})}/><footer><span>{doc.wordCount} words</span><span>{doc.content.length} characters</span><span>Saved locally</span></footer></section>:<Empty icon={DocumentTextIcon} title="Your writing room is ready" text="Create a document and give the story a little space to speak." action={create}/>}</div>}

const structureFields=[['premise','Premise','Your story in one compelling sentence.'],['theme','Theme','The question or truth beneath the plot.'],['mainConflict','Main conflict','What keeps the protagonist from what they need?'],['beginning','Beginning','The world before everything changes.'],['incitingIncident','Inciting incident','The event that makes going back impossible.'],['midpoint','Midpoint','The revelation that changes the game.'],['crisis','Crisis','The moment all seems lost.'],['climax','Climax','The final choice and confrontation.'],['ending','Ending','The new world after the storm.'],['subplots','Subplots','Secondary threads that echo the theme.'],['characterArcs','Character arcs','Who must each person become?'],['timeline','Timeline','The story’s essential chronology.'],['openQuestions','Open questions','What still needs an answer?']];
function Structure({p,save}:{p:Project;save:(x:Record<string,string|undefined>)=>void}){return <section className="structuregrid">{structureFields.map(([k,t,h],i)=><article key={k} className={i===0?'wide':''}><span>{String(i+1).padStart(2,'0')}</span><h3>{t}</h3><p>{h}</p><textarea rows={i===0?4:5} value={p.bookStructure[k]||''} onChange={e=>save({...p.bookStructure,[k]:e.target.value})} placeholder="Write gently. This can change."/></article>)}</section>}

function Scenes({items,save}:{items:Scene[];save:(x:Scene[])=>void}){const statuses=['idea','to_write','drafted','needs_revision','final'];const add=(status:string)=>{const title=prompt('Scene title');if(title)save([...items,{id:uid(),title,status,characterIds:[],createdAt:stamp(),updatedAt:stamp()}])};return <div className="board">{statuses.map(status=><section key={status}><header><span>{pretty(status)}</span><b>{items.filter(x=>x.status===status).length}</b></header>{items.filter(x=>x.status===status).map(s=><article key={s.id}><h3>{s.title}</h3><p>{s.purpose||s.keyEvent||'A scene waiting for its purpose.'}</p><footer><select value={s.status} onChange={e=>save(items.map(x=>x.id===s.id?{...x,status:e.target.value}:x))}>{statuses.map(v=><option value={v} key={v}>{pretty(v)}</option>)}</select><button onClick={()=>confirm('Delete this scene?')&&save(items.filter(x=>x.id!==s.id))}><TrashIcon/></button></footer></article>)}<button className="addcard" onClick={()=>add(status)}><PlusIcon/>Add scene</button></section>)}</div>}

function Generic({title,items,save}:{title:string;items:GenericItem[];save:(x:GenericItem[])=>void}){const [edit,setEdit]=useState<GenericItem|null>(null);const fresh=()=>setEdit({id:uid(),title:'',description:'',createdAt:stamp(),updatedAt:stamp()});return <>{items.length?<div className="genericgrid">{items.map((x,i)=><article key={x.id}><span>{String(i+1).padStart(2,'0')}</span><h3>{x.title}</h3><p>{x.description||x.content||'No notes yet.'}</p><button className="textbtn" onClick={()=>setEdit(x)}>Edit <ArrowRightIcon/></button></article>)}</div>:<Empty icon={SparklesIcon} title={`Your ${title.toLowerCase()} is open`} text="Add the first piece. It does not need to be polished to be useful." action={fresh}/>}<button className="primary below" onClick={fresh}><PlusIcon/>Add item</button>{edit&&<Modal title={edit.title||`New ${title.toLowerCase()} item`} close={()=>setEdit(null)}><Field label="Title"><input autoFocus value={edit.title} onChange={e=>setEdit({...edit,title:e.target.value})}/></Field><Field label="Notes"><textarea rows={8} value={edit.description||''} onChange={e=>setEdit({...edit,description:e.target.value})}/></Field><ModalActions remove={items.some(x=>x.id===edit.id)?()=>{save(items.filter(x=>x.id!==edit.id));setEdit(null)}:undefined} save={()=>{if(!edit.title.trim())return;save(items.some(x=>x.id===edit.id)?items.map(x=>x.id===edit.id?edit:x):[...items,edit]);setEdit(null)}}/></Modal>}</>}

function Settings({p,save,remove}:{p:Project;save:(x:Project)=>void;remove:()=>void}){const [x,setX]=useState(p);const download=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(x,null,2)],{type:'application/json'}));a.download=`${x.title.toLowerCase().replace(/\W+/g,'-')}.json`;a.click()};return <section className="paperform"><Field label="Title"><input value={x.title} onChange={e=>setX({...x,title:e.target.value})}/></Field><div className="formrow"><Field label="Format"><Select value={x.type} onChange={v=>setX({...x,type:v as Project['type']})} options={['novel','short_story','saga','collection','other']}/></Field><Field label="Genre"><Select value={x.genre} onChange={v=>setX({...x,genre:v as Project['genre']})} options={['fantasy','romance','thriller','drama','young_adult','contemporary','other']}/></Field><Field label="Status"><Select value={x.status} onChange={v=>setX({...x,status:v as Project['status']})} options={['idea','planning','drafting','editing','finished']}/></Field></div><Field label="Description"><textarea rows={4} value={x.description||''} onChange={e=>setX({...x,description:e.target.value})}/></Field><Field label="Cover image URL"><input value={x.coverUrl||''} onChange={e=>setX({...x,coverUrl:e.target.value})}/></Field><div className="settingsactions"><button className="danger" onClick={remove}><TrashIcon/>Delete project</button><button className="ghost" onClick={download}>Export JSON</button><button className="primary" onClick={()=>save(x)}><CheckIcon/>Save changes</button></div></section>}

function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
function Select({value,onChange,options}:{value:string;onChange:(s:string)=>void;options:string[]}){return <select value={value} onChange={e=>onChange(e.target.value)}>{options.map(x=><option value={x} key={x}>{pretty(x)}</option>)}</select>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="modalback" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal"><header><div><p className="eyebrow">Character atelier</p><h2>{title}</h2></div><button onClick={close}><XMarkIcon/></button></header><div className="modalbody">{children}</div></div></div>}
function ModalActions({remove,save}:{remove?:()=>void;save:()=>void}){return <div className="modalactions">{remove&&<button className="danger" onClick={()=>confirm('Delete this item?')&&remove()}><TrashIcon/>Delete</button>}<span/><button className="primary" onClick={save}><CheckIcon/>Save</button></div>}
function Empty({icon:I,title,text,action}:{icon:typeof SparklesIcon;title:string;text:string;action?:()=>void}){return <div className="empty"><span><I/></span><h3>{title}</h3><p>{text}</p>{action&&<button className="primary" onClick={action}><PlusIcon/>Add the first one</button>}</div>}
function MobileNav({go,project}:{go:(s:string)=>void;project?:Project}){return <nav className="mobileNav"><button onClick={()=>go('/')}><HomeIcon/><span>Home</span></button><button onClick={()=>go(project?`/projects/${project.id}/characters`:'/')}><UsersIcon/><span>People</span></button><button className="mobileAdd" onClick={()=>go(project?`/projects/${project.id}/ideas`:'/projects/new')}><PlusIcon/></button><button onClick={()=>go(project?`/projects/${project.id}/writing`:'/')}><DocumentTextIcon/><span>Write</span></button><button onClick={()=>go(project?`/projects/${project.id}`:'/')}><BookOpenIcon/><span>Project</span></button></nav>}
function NotFound({go}:{go:(s:string)=>void}){return <main className="page"><Empty icon={BookOpenIcon} title="This page wandered out of the story" text="Let’s return to the atelier and find the right thread." action={()=>go('/')}/></main>}
