import {Project} from './types';
import {uid} from './id';
const now='2026-06-18T18:20:00.000Z';
export const emptyProject=(values:Partial<Project>):Project=>({id:uid(),title:'Untitled story',type:'novel',genre:'fantasy',status:'idea',description:'',progress:0,characters:[],worldbuilding:[],chapters:[],scenes:[],relationships:[],plotTwists:[],randomIdeas:[],writingDocuments:[],bookStructure:{},moodboard:[],customSections:[],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),...values});
export const demoProjects:Project[]=[{
 id:'glass-kingdom',title:'The Glass Kingdom',type:'novel',genre:'fantasy',status:'drafting',description:'In a kingdom made of living crystal, a young archivist discovers that every reflection hides a memory the crown tried to erase.',progress:65,coverUrl:'https://images.unsplash.com/photo-1518562180175-34a163b1a9a6?auto=format&fit=crop&w=900&q=80',createdAt:now,updatedAt:now,
 characters:[{id:'elara',name:'Elara Vale',role:'protagonist',age:'24',personality:'Restless, observant, quietly brave.',mainGoal:'Restore the stolen memories of her city.',fear:'Becoming as cold as the crystal court.',secret:'She can walk through reflections.',tags:['archivist','glasswalker'],createdAt:now,updatedAt:now},{id:'kaelen',name:'Kaelen Thorne',role:'antagonist',age:'31',personality:'Controlled, magnetic, merciless when cornered.',tags:['heir','rival'],createdAt:now,updatedAt:now}],
 chapters:[{id:'c1',number:1,title:'The Shattered Lens',status:'finished',keyPoints:['Elara finds the forbidden lens'],wordCount:3480,createdAt:now,updatedAt:now},{id:'c2',number:2,title:'Echoes of the Archive',status:'drafted',keyPoints:['The archive begins to speak'],wordCount:2710,createdAt:now,updatedAt:now},{id:'c3',number:3,title:'Unseen Cracks',status:'planned',keyPoints:[],wordCount:0,createdAt:now,updatedAt:now}],
 scenes:[{id:'s1',title:'The library infiltration',status:'to_write',characterIds:['elara'],purpose:'Reveal the map inside the mirror',createdAt:now,updatedAt:now},{id:'s2',title:'Midnight escape',status:'idea',characterIds:['elara','kaelen'],createdAt:now,updatedAt:now},{id:'s3',title:'The first fracture',status:'drafted',characterIds:['elara'],createdAt:now,updatedAt:now}],
 randomIdeas:[{id:'i1',text:'What if the palace remembers everyone who has lied inside it?',tags:['world','magic'],pinned:true,createdAt:now,updatedAt:now}],writingDocuments:[{id:'d1',title:'Chapter one draft',chapterId:'c1',content:'The first crack appeared at midnight, thin as a strand of silver hair.',wordCount:12,createdAt:now,updatedAt:now}],
 bookStructure:{premise:'A memory-keeper must break the magical system she was raised to protect.',theme:'The stories we bury still shape us.',mainConflict:'Truth versus the safety of a beautiful lie.',beginning:'Elara discovers a lens carrying a forbidden memory.',midpoint:'She learns her mother created the first fracture.'},
 worldbuilding:[{id:'w1',title:'The Refraction Chambers',category:'location',description:'A cathedral of prisms where memories are catalogued.',createdAt:now,updatedAt:now}],relationships:[],plotTwists:[],moodboard:[],customSections:[]
},{...emptyProject({id:'summer-rain',title:'Summer Rain',type:'short_story',genre:'romance',status:'planning',description:'Two old friends, one seaside bookshop, and the summer they finally stop missing each other.',progress:28}),createdAt:now,updatedAt:now,randomIdeas:[{id:'i2',text:'A postcard arrives twelve summers late.',tags:['opening'],pinned:false,createdAt:now,updatedAt:now}]}];
